function [data,brand] = proc(filename)
%read the battery.txt file generated by extractBattery.py
fid=fopen(filename);
A=textscan(fid, '%f%f%f%s');
%A{1} date; A{2} battery; A{3} size; A{4} brand
data=[A{1} A{2} A{3}];
brand=A{4};
end

